name: Fullstack Build & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # All steps run in /backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Auto-caches ~/.m2

      - name: Build and Test with Maven
        run: mvn clean package

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar  # For deployment later

  frontend:
    runs-on: ubuntu-latest
    needs: backend  # Optional: Wait for backend to finish first
    defaults:
      run:
        working-directory: ./frontend  # All steps run in /frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  # Auto-caches node_modules

      - name: Install and Build React
        run: |
          npm ci
          npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build/  # For deployment later